launch from JugglingLab.jar if present (macOS)

diff --git a/bin/jlab b/bin/jlab
--- a/bin/jlab
+++ b/bin/jlab
@@ -7,31 +7,56 @@
 
 
 DIR=$(dirname "$0")
+JL_JAR="${DIR}/JugglingLab.jar"
+
 export JL_WORKING_DIR="`pwd`"
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
-    # running on macOS; launch using executable in application bundle
+    # Running on macOS; first try launching in JugglingLab.jar in same directory
+    if [ -a "${JL_JAR}" ]; then
+        if type java >/dev/null 2>&1; then
+            _java=java
+        elif [[ -n "${JAVA_HOME}" ]] && [[ -x "${JAVA_HOME}/bin/java" ]]; then
+            _java="${JAVA_HOME}/bin/java"
+        fi
+
+        if [[ "$_java" ]]; then
+            version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+            version1=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
+            if [ "$version1" -ge "011000" ]; then
+                if [[ $# -ne 0 ]]; then
+                    "$_java" -cp "${JL_JAR}:commons-math3-3.6.1.jar:protobuf.jar:com.google.ortools.jar" -Xss2048k -Djava.library.path=ortools-lib jugglinglab.JugglingLab ${1+"$@"}
+                    exit 1
+                else
+                    # print a help message if no command line args
+                    "$_java" -cp "${JL_JAR}" jugglinglab.JugglingLab help
+                    exit 1
+                fi
+            fi
+        fi
+    fi
+
+    # Then try launching in the application bundle
     OSX_JL_EXEC="${DIR}/Juggling Lab.app/Contents/MacOS/Juggling Lab"
 
     if [[ -x "${OSX_JL_EXEC}" ]]; then
         if [[ $# -ne 0 ]]; then
             "${OSX_JL_EXEC}" ${1+"$@"}
+            exit 1
         else
             # print a help message if no command line args
             "${OSX_JL_EXEC}" help
+            exit 1
         fi
-    else
-        echo >&2 "\"Juggling Lab.app\" not found in same directory as this script."
-        exit 1
     fi
+
+    echo >&2 "\"Juggling Lab.app\" not found in same directory as this script."
 else
-    # running on other OS. Make sure an adequate version of Java is installed,
+    # Running on other OS. Make sure an adequate version of Java is installed,
     # then launch the jar.
     if type java >/dev/null 2>&1; then
-        # echo found java executable in PATH
         _java=java
     elif [[ -n "${JAVA_HOME}" ]] && [[ -x "${JAVA_HOME}/bin/java" ]]; then
-        # echo found java executable in \$JAVA_HOME
         _java="${JAVA_HOME}/bin/java"
     else
         echo >&2 "Java not found. Be sure Java 11 or higher is installed and \$JAVA_HOME"
@@ -42,23 +67,22 @@ else
     if [[ "$_java" ]]; then
         version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
         version1=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
-        if [ "$version1" \< "011000" ]; then
+        if [ "$version1" -lt "011000" ]; then
             echo >&2 "Java installed is version ${version}; need Java 11 or higher to run."
             exit 1
         fi
     fi
 
-    JL_JAR="${DIR}/JugglingLab.jar"
-
     if [ -a "${JL_JAR}" ]; then
         if [[ $# -ne 0 ]]; then
             "$_java" -cp "${JL_JAR}:commons-math3-3.6.1.jar:protobuf.jar:com.google.ortools.jar" -Xss2048k -Djava.library.path=ortools-lib jugglinglab.JugglingLab ${1+"$@"}
+            exit 1
         else
             # print a help message if no command line args
             "$_java" -cp "${JL_JAR}" jugglinglab.JugglingLab help
+            exit 1
         fi
-    else
-        echo >&2 "\"JugglingLab.jar\" not found in same directory as this script."
-        exit 1
     fi
+
+    echo >&2 "\"JugglingLab.jar\" not found in same directory as this script."
 fi
