look for macOS application in Applications directory

diff --git a/bin/jlab b/bin/jlab
--- a/bin/jlab
+++ b/bin/jlab
@@ -13,7 +13,7 @@ export JL_WORKING_DIR="`pwd`"
 if [[ "$OSTYPE" == "darwin"* ]]; then
     # Running on macOS
 
-    # first try launching in JugglingLab.jar in same directory
+    # First try launching in JugglingLab.jar in same directory
     if [ -a "${JL_JAR}" ]; then
         if type java >/dev/null 2>&1; then
             _java=java
@@ -40,6 +40,9 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
 
     # Then try launching in the application bundle
     OSX_JL_EXEC="${DIR}/Juggling Lab.app/Contents/MacOS/Juggling Lab"
+    if ! [[ -x "${OSX_JL_EXEC}" ]]; then
+        OSX_JL_EXEC="/Applications/Juggling Lab.app/Contents/MacOS/Juggling Lab"
+    fi
 
     if [[ -x "${OSX_JL_EXEC}" ]]; then
         if [[ $# -ne 0 ]]; then
@@ -52,11 +55,11 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
         fi
     fi
 
-    echo >&2 "\"Juggling Lab.app\" not found in same directory as this script."
+    echo >&2 "\"Juggling Lab.app\" not found."
 else
     # Running on other Unix
 
-    # first try launching in JugglingLab.jar in same directory
+    # First try launching in JugglingLab.jar in same directory
     if [ -a "${JL_JAR}" ]; then
         if type java >/dev/null 2>&1; then
             _java=java
@@ -69,7 +72,7 @@ else
             version1=$(echo "$version" | awk -F. '{printf("%03d%03d",$1,$2);}')
             if [ "$version1" -ge "011000" ]; then
                 if [[ $# -ne 0 ]]; then
-                    "$_java" -cp "${JL_JAR}" -Xss2048k -Djava.library.path=ortools-lib/ortools-linux-x86-64 jugglinglab.JugglingLab ${1+"$@"}
+                    "$_java" -cp "${JL_JAR}" -Xss2048k -Djava.library.path=ortools-lib/ortools-linux-x86-64:ortools-lib/ortools-linux-aarch64 jugglinglab.JugglingLab ${1+"$@"}
                     exit 1
                 else
                     # print a help message if no command line args
